### ISSUE TITLE
老哥 https://github.com/chineseocr/chineseocr   

### ISSUE THREAD

**Issue by zyjcs** [StringKe/SClient#1]
这个项目出现[图片][图片] 

tf1.14 报这个错，  代码里面有feed_dict啊 在tf1.8跑没问题  

出现这个问题 你是怎么解决的 啊  可以加下Q吗  1136899882  谢谢

**Comment by zyjcs** [comment]
![image](https://user-images.githubusercontent.com/18757695/63755821-eb2c6080-c8e9-11e9-9408-2e3f0bc033a6.png)

**Comment by StringKe** [comment]
模型下载了么？
